# action.yml
name: 'DECTalk_TTV'
on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Software Reqs
        run: python -m pip install -r requirements.txt

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: ~/repo

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          path: ~/repo
          context: ./
          file: '/pwpush-ephemeral/Dockerfile'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pwpush-ephemeral:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}